# Generated by Django 4.1.3 on 2022-11-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=100)),
                ('pesel', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=45)),
                ('houseNumber', models.IntegerField(max_length=3)),
                ('flatNumber', models.IntegerField(max_length=3)),
                ('postcode', models.CharField(max_length=11)),
                ('placeName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('zone', models.CharField(max_length=45)),
                ('dateOfPurchase', models.DateTimeField()),
                ('dateOfEnd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=45)),
                ('houseNumber', models.IntegerField(max_length=3)),
                ('flatNumber', models.IntegerField(max_length=3)),
                ('postcode', models.IntegerField(max_length=45)),
                ('placeName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.IntegerField(max_length=9)),
                ('email', models.CharField(max_length=100)),
                ('pesel', models.IntegerField(max_length=11)),
                ('workerAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workeraddress')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker'),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientadress'),
        ),
    ]
