# Generated by Django 4.1.3 on 2022-11-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.IntegerField(max_length=9),
        ),
    ]
