# Generated by Django 4.1.3 on 2022-11-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='workerAddress',
        ),
        migrations.AddField(
            model_name='workeraddress',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.worker'),
        ),
    ]
