# Generated by Django 4.1.3 on 2022-11-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_worker_workeraddress_workeraddress_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adress',
        ),
        migrations.AddField(
            model_name='clientadress',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='clientadress',
            name='flatNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientadress',
            name='houseNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phoneNumber',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='workeraddress',
            name='flatNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workeraddress',
            name='houseNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workeraddress',
            name='postcode',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='workeraddress',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker'),
        ),
    ]
