# Generated by Django 4.1.3 on 2022-11-29 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_ticket_dateofpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 15, 25, 7, 576884)),
        ),
    ]
