# Generated by Django 4.1.3 on 2022-11-29 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_clientadress_clientaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 15, 42, 37, 452825)),
        ),
    ]
