# Generated by Django 4.1.3 on 2023-01-10 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_client_email_alter_clientaddress_flatnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 13, 54, 17, 509169)),
        ),
    ]
