# Generated by Django 4.1.3 on 2023-01-10 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_ticket_dateofpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='slugField',
            field=models.SlugField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 14, 32, 48, 180413)),
        ),
    ]
