# Generated by Django 4.1.3 on 2023-01-14 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_worker_slugfield_alter_ticket_dateofpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='flatNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 14, 13, 45, 935819)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='zone',
            field=models.CharField(choices=[('Pływalnia', 'Pływalnia'), ('SPA', 'SPA'), ('Siłownia', 'Siłownia')], max_length=45),
        ),
    ]
