# Generated by Django 4.1.3 on 2023-01-14 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_clientaddress_flatnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='description',
            field=models.CharField(choices=[('1 zmiana', '1 zmiana'), ('2 zmiana', '2 zmiana')], max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 14, 16, 0, 243752)),
        ),
    ]
