# Generated by Django 4.1.3 on 2023-01-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_ticket_dateofpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateOfEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
