# Generated by Django 4.1.3 on 2023-01-14 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_ticket_dateofpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateOfEnd',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateOfPurchase',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 16, 9, 1, 108546), editable=False),
        ),
    ]
